name: Publish API Worker & Web Pages

on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish API Worker & Web Pages
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

      - name: Check VARS
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: echo "THE URL is $VITE_API_URL"

      - name: Publish API worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_WORKERS_TOKEN }}
        run: cd ./apps/api && pnpm run publish

      - name: Publish Web Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_PAGES_TOKEN }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: cd ./apps/web && pnpm run publish
